spring:
  profiles:
    active: test
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            #这里有个allowCredentials: true这个东西是设置允许访问携带cookie的，这点一定要和前端对应！
            allowCredentials: true
            #可以填写多个域名用","隔开 例如：""  "*"代表允许所有
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1
  security:
    oauth2:
      client:
        provider: dfd
        registration: