server:
  port: 9001

eureka:
  instance:
    hostname: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}:${random.value}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
  server:
    enable-self-preservation: false # 关闭自我保护模式（缺省为打开）生产环境要打开
    # 扫描失效服务的间隔时间（单位毫秒，默认是60*1000）即60秒  生产环境下，需要自我保护机制，需注释
    eviction-interval-timer-in-ms: 2000
    use-read-only-response-cache: false
    response-cache-update-interval-ms: 2000
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    registry-fetch-interval-seconds: 5    #eureka client刷新本地缓存时间  #默认30s
    service-url:
      #单机
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    initial-instance-info-replication-interval-seconds: 10